import React, { useEffect, useMemo, useRef, useState } from "react";
import { useNavigate } from "react-router-dom";
import api from "../../lib/api.js";
import Card from "../../components/Card.jsx";
import Button from "../../components/Button.jsx";
import Field from "../../components/Field.jsx";

import "../../styles/layout/appPages.css";

const CHAT_ENDPOINT = "/api/chatbot";

export default function Chatbot() {
  const nav = useNavigate();

  const [input, setInput] = useState("");
  const [sending, setSending] = useState(false);
  const [error, setError] = useState("");

  const [messages, setMessages] = useState([]);
  const canSend = useMemo(
    () => input.trim().length > 0 && !sending,
    [input, sending]
  );

  const convoRef = useRef(null);

  useEffect(() => {
    const el = convoRef.current;
    if (!el) return;
    el.scrollTop = el.scrollHeight;
  }, [messages.length]);

  const onSend = async () => {
    const text = input.trim();
    if (!text || sending) return;

    setError("");
    setSending(true);
    setMessages((m) => [...m, { role: "user", text }]);
    setInput("");

    try {
      // Backend expects: { messages: [{ role, content }, ...] }
      const payload = {
        messages: [
          ...messages.map((m) => ({ role: m.role, content: m.text })),
          { role: "user", content: text }
        ]
      };

      const res = await api.post(CHAT_ENDPOINT, payload);

      // Backend returns: { role, content }
      const replyText =
        res?.data?.content ??
        res?.data?.reply ??
        res?.data?.message ??
        (typeof res?.data === "string" ? res.data : "");

      setMessages((m) => [
        ...m,
        {
          role: "assistant",
          text: replyText ? String(replyText) : "No reply received."
        }
      ]);
    } catch (err) {
      console.error("Chatbot send failed:", err);
      setError(
        err?.response?.data?.error ||
          err?.response?.data?.message ||
          err?.message ||
          "Failed to send message."
      );
    } finally {
      setSending(false);
    }
  };

  const onClear = () => {
    if (sending) return;
    setError("");
    setMessages([]);
    setInput("");
  };

  return (
    <div className="page">
      <div className="panel">
        <div className="pageHeader">
          <div className="pageHeaderText">
            <h1 className="pageTitle">AI Chatbot</h1>
            <div className="pageSubtitle">
              Messages are sent to the backend. AI memory is handled server-side.
              <br />
              OpenAI (server-managed memory)
            </div>

            {error ? (
              <div
                style={{
                  marginTop: 10,
                  padding: 10,
                  borderRadius: 12,
                  border: "1px solid rgba(255,0,0,0.25)",
                  background: "rgba(255,0,0,0.08)",
                  wordBreak: "break-word"
                }}
              >
                {error}
              </div>
            ) : null}
          </div>

          <div className="pageHeaderRight">
            <Button variant="ghost" onClick={() => nav("/dashboard")}>
              Dashboard
            </Button>

            <Button variant="ghost" onClick={onClear} disabled={sending}>
              Clear
            </Button>
            <Button onClick={onSend} disabled={!canSend}>
              {sending ? "Sending…" : "Send"}
            </Button>
          </div>
        </div>

        <div className="pageBody" style={{ display: "grid", gap: 16 }}>
          <div
            style={{
              display: "grid",
              gap: 16,
              gridTemplateColumns: "repeat(auto-fit, minmax(320px, 1fr))",
              alignItems: "start"
            }}
          >
            <Card
              title="Conversation"
              subtitle="AI responses are generated by the backend."
            >
              {messages.length === 0 ? (
                <div className="muted">No messages yet.</div>
              ) : (
                <div
                  ref={convoRef}
                  style={{
                    display: "grid",
                    gap: 10,
                    maxHeight: "clamp(280px, 45vh, 520px)",
                    overflow: "auto",
                    paddingRight: 6,
                    overscrollBehavior: "contain"
                  }}
                >
                  {messages.map((m, idx) => {
                    const isUser = m.role === "user";
                    return (
                      <div
                        key={idx}
                        style={{
                          display: "grid",
                          gap: 6,
                          justifyItems: isUser ? "end" : "start"
                        }}
                      >
                        <div
                          className="muted"
                          style={{
                            fontSize: 12,
                            textAlign: isUser ? "right" : "left"
                          }}
                        >
                          {isUser ? "You" : "AI"}
                        </div>

                        <div
                          style={{
                            maxWidth: "min(760px, 100%)",
                            padding: "10px 12px",
                            borderRadius: 14,
                            border: "1px solid var(--border)",
                            background: isUser
                              ? "rgba(0,0,0,0.22)"
                              : "rgba(255,255,255,0.10)",
                            lineHeight: 1.45,
                            whiteSpace: "pre-wrap",
                            wordBreak: "break-word",
                            overflowWrap: "anywhere"
                          }}
                        >
                          {m.text}
                        </div>
                      </div>
                    );
                  })}
                </div>
              )}
            </Card>

            <Card title="Message" subtitle="Message sent to backend via axios/api client.">
              <div style={{ display: "grid", gap: 10 }}>
                <Field label="Your message">
                  <textarea
                    className="textarea"
                    value={input}
                    onChange={(e) => setInput(e.target.value)}
                    placeholder="Type your message…"
                    rows={5}
                    style={{ resize: "vertical", minHeight: 110 }}
                    onKeyDown={(e) => {
                      if ((e.metaKey || e.ctrlKey) && e.key === "Enter") {
                        e.preventDefault();
                        onSend();
                      }
                    }}
                  />
                </Field>

                <div
                  className="row"
                  style={{
                    justifyContent: "flex-end",
                    gap: 10,
                    flexWrap: "wrap"
                  }}
                >
                  <Button variant="ghost" onClick={onClear} disabled={sending}>
                    Clear
                  </Button>
                  <Button onClick={onSend} disabled={!canSend}>
                    {sending ? "Sending…" : "Send"}
                  </Button>
                </div>

                <div className="muted" style={{ fontSize: 12 }}>
                  Tip: Use Ctrl+Enter (Windows/Linux) or ⌘+Enter (Mac) to send.
                </div>
              </div>
            </Card>
          </div>
        </div>
      </div>
    </div>
  );
}