import React, { useRef, useState , useEffect} from "react";
import Card from "../../components/Card.jsx";
import Field from "../../components/Field.jsx";
import Button from "../../components/Button.jsx";


import { apiFetch } from "../../api/client";

export default function Chatbot() {

  const [messages, setMessages] = useState([]);
  const [text, setText] = useState("");
  const [error, setError] = useState(null);
  const endRef = useRef(null);

  useEffect(() => {
    endRef.current?.scrollIntoView({ behavior: "smooth" });
  }, [messages]);
  
  const send = async () => {
    setError(null);

    if (!text.trim()) {
      setError("Message is required");
      return;
    }

    try {
      const res = await apiFetch("/api/chatbot", {
        method: "POST",
        body: JSON.stringify({
          messages: [
            ...messages.flatMap(m => ([
              { role: "user", content: m.user_message },
              { role: "assistant", content: m.ai_response }
            ])),
            { role: "user", content: text.trim() }
          ]
        })
      });

      setMessages(prev => [
        ...prev,
        {
          user_message: text.trim(),
          ai_response: res.content
        }
      ]);

      setText("");
      
    } catch (err) {
      setError(err.message || "Failed to send message");
    }
  };

  return (
    <div style={{ display: "grid", gap: 12 }}>
      <div className="row">
        <div>
          <h1 className="h1">AI Chatbot</h1>
          <div className="muted">
            Messages are sent to the backend; AI memory is handled server-side.
          </div>
        </div>
        <div className="spacer" />
        <span className="badge">OpenAI (server-managed memory)</span>
      </div>

      <Card
        title="Conversation"
        subtitle="AI responses are generated by the backend"
      >
        <div
          style={{
            display: "grid",
            gap: 10,
            maxHeight: 420,
            overflow: "auto",
            paddingRight: 4,
          }}
        >
          {messages.length === 0 ? (
            <div className="muted">No messages yet.</div>
          ) : (
            messages.map((m, i) => (
              <div key={i} style={{ display: "grid", gap: 6 }}>
                <div
                  style={{
                    border: "1px solid var(--border)",
                    borderRadius: 12,
                    padding: 10,
                  }}
                >
                  <div className="muted" style={{ fontSize: 12 }}>
                    You
                  </div>
                  <div>{m.user_message}</div>
                </div>

                <div
                  style={{
                    border: "1px solid rgba(122,162,255,0.35)",
                    borderRadius: 12,
                    padding: 10,
                    background: "rgba(122,162,255,0.08)",
                  }}
                >
                  <div className="muted" style={{ fontSize: 12 }}>
                    AI
                  </div>
                  <div>{m.ai_response}</div>
                </div>
              </div>
            ))
          )}
          <div ref={endRef} />
        </div>

        <div className="hr" />

        <Field
          label="Message"
          error={error}
          hint="Sent to backend via axios"
        >
          <textarea
            className="textarea"
            value={text}
            onChange={(e) => setText(e.target.value)}
          />
        </Field>

        <div className="row">
          <Button onClick={send}>Send</Button>
          <div className="spacer" />
          <span className="muted" style={{ fontSize: 13 }}>
            Conversation memory is server-managed.
          </span>
        </div>
      </Card>
    </div>
  );
};
